//  Q no 22
var Friends = ["Amir", "Adil", "Wakeel", "Raheel"];
console.log(Friends[4]);
Friends[3] = "Raheel";
console.log(Friends[3]);
// Q no 23
var Car = "Corolla";
console.log("is Car ==='Corolla'? I predict true");
console.log(Car === "Corolla");
console.log("is Car ==='Marsadies'? I predict false");
console.log(Car === "Marsadies");
var Color = "Green";
console.log("is Color ==='Green'? I predict true");
console.log(Color === "Green");
console.log("is Color ==='red'? I predict false");
console.log(Color === "red");
var Watch = "Rado";
console.log("is Watch ==='Rado'? I predict true");
console.log(Watch === "Rado");
console.log("is Watch ==='Seico5'? I predict false");
console.log(Watch === "Seico5");
var Pen = "Dux";
console.log("is Pen ==='Dux'? I predict true");
console.log(Pen === "Dux");
console.log("is Pen ==='Dolor'? I predict false");
console.log(Pen === "Dolor");
var Stadium = "National Stadium Karachi";
console.log("is Stadium ==='National Stadium Karachi'? I predict true");
console.log(Stadium === "National Stadium Karachi");
console.log("is Stadium ==='Khazafi Stadium Lahore'? I predict false");
console.log(Watch === "Khazafi Stadium Lahore");
//  Q no 24
console.log("'Safdar'=='Safdar'");
console.log('safdar' == 'safdar');
console.log("5 == 5");
console.log(5 == 5);
console.log("true == true");
console.log(true == true);
console.log('is 10 > 8?');
console.log(10 > 8);
console.log('is 10 < 8?');
console.log(10 < 8);
console.log(true && false);
console.log(true || false);
var Fruits = ["Apple", "Mango", "Banana"];
console.log("Is 'Apple' in fruits?");
console.log(Fruits.includes("Apple"));
console.log("Is 'Charry' in fruits?");
console.log(Fruits.includes("Charry"));
